name: OCR PDF Action
# Define when to run job here
on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Runing OCR PDF Action
    steps:
    - uses: MarketingPipeline/OCR-PDF-Action@main
      with:
        # Define the folder or file to download
        input_file: .github/example_pdfs/Non-text-searchable.pdf
        output_file: .github/example_pdfs/output_searchable.pdf
